### ISSUE TITLE
--restart will not work with this docker

### ISSUE THREAD

**Issue by waynebrantley** [s12v/newrelic-elasticsearch-docker#1]
The docker runs this command.
./npi start me.snov.newrelic-elasticsearch --foreground

When the docker is stopped, it does not stop cleanly and has an exit code of 137.  This causes docker to not attempt to restart it the next time.  This usually indicates it did not handle SIGTERM, but instead SIGKILL.

The docker file in this project uses the 'shell form' of what to run with 

`CMD command param1 param2`

/bin/sh will not forward SIGTERM to the process it is running, so it will never exit cleanly.

If we use the EXEC form of the cmd, which looks like:
`CMD ["command",:param1", "param2"]`

This will run the command without a shell, so the npi process will receive the SIGTERM.

To do this, I am thinking you will need to run your startup.sh script as a normal RUN command in the docker (without the final run).
Then the CMD would simply be 
`CMD["./npi start me.snov.newrelic-elasticsearch --foreground"]`

Also, optionally, just run it in the background?

**Comment by s12v** [comment]
Fixed in https://github.com/s12v/newrelic-elasticsearch-docker/pull/5
